# Generated by Django 5.2 on 2025-05-10 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_profile_picture_alter_profile_bio_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Episode",
        ),
        migrations.DeleteModel(
            name="Story",
        ),
        migrations.DeleteModel(
            name="StoryReport",
        ),
        migrations.DeleteModel(
            name="Version",
        ),
    ]
