# Generated by Django 5.2.1 on 2025-05-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_delete_episode_delete_story_delete_storyreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("subadmin", "Subadmin"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=10,
            ),
        ),
    ]
