# Generated by Django 5.2.1 on 2025-06-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
