# Generated by Django 5.2 on 2025-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0003_episode_created_at_episode_parent_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="story_covers/"),
        ),
        migrations.AddField(
            model_name="story",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
