# Generated by Django 5.2 on 2025-05-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0004_story_cover_image_story_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="parent_version",
        ),
        migrations.AddField(
            model_name="episode",
            name="parent_episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_episodes",
                to="storyapp.episode",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
