# Generated by Django 5.2.1 on 2025-05-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "storyapp",
            "0005_remove_episode_parent_version_episode_parent_episode_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="next_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous",
                to="storyapp.version",
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="previous_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next",
                to="storyapp.version",
            ),
        ),
    ]
