# Generated by Django 5.2.1 on 2025-05-14 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0006_version_next_version_version_previous_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="version",
            name="next_version",
        ),
        migrations.RemoveField(
            model_name="version",
            name="previous_version",
        ),
    ]
