# Generated by Django 5.2.1 on 2025-05-15 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0007_remove_version_next_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="episode",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
