# Generated by Django 5.2.1 on 2025-05-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0009_alter_story_visibility_episodereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="status",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("quarantined", "Quarantined"),
                    ("reported", "Reported"),
                ],
                default="public",
                max_length=15,
            ),
        ),
    ]
