# Generated by Django 5.2.1 on 2025-05-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0011_alter_episode_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="status",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("quarantined", "Quarantined"),
                    ("reported", "Reported"),
                    ("pending", "Pending"),
                    ("deleted", "Deleted"),
                ],
                default="public",
                max_length=15,
            ),
        ),
    ]
