# Generated by Django 5.2.1 on 2025-05-23 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0012_alter_episode_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episodereport",
            options={"ordering": ["-created_at"]},
        ),
    ]
