# Generated by Django 5.2.1 on 2025-06-05 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0013_alter_episodereport_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_episodes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
