# Generated by Django 5.2.1 on 2025-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storyapp", "0016_storyinvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyinvite",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
